// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let num1 = 1;
let num2 = 2;
let sum = 0;

while( num1 < 4000000) {

    if( num1 % 2 === 0){
        sum += num1;
    }

    //update a and b through each while iteration, ex. for 1st iteration through:
    let num3 = num1 + num2; // 3 = 1 + 2
    num1 = num2; // 1 = 2, now
    num2 = num3; // 2 = 3, now
}

console.log(sum)
